### ISSUE TITLE
Download button isn't working

### ISSUE THREAD

**Issue by TalmarGrosskotz** [piatra/kreator.js#43]
Sucessfully installed kreator.js on my homeserver.

Starts up fine.. Editor working. 
But the Download-Button doesn't work at all. Clicking it doesn't have any effect.

**Comment by piatra** [comment]
Can you provide a screenshot of the web console ? I'll look into it.

**Comment by TalmarGrosskotz** [comment]
Screenshot was difficult at the moment but i get a message like this

code 404, message File not found
“GET /kreator.js/download/beige.css HTTP/1.1” 404 -

​
Hope that can help.

Jörg

2016-02-23 21:24 GMT+01:00 Andrei Oprea <notifications@github.com>:

**Comment by FancyFane** [comment]
Download is not working for me either, on a freshly installed instance. Inspecting my Firefox console as soon as I click download I get the following error: 

[Q] Unhandled rejection reasons (should be empty): Array [ "onload@https://kreator.myurl.com…" ]

I'm not sure if its relevant, but I'm using nginx as a proxy, to allow for encrypted communication to the kreator application.

**Comment by FancyFane** [comment]
I believe I have a resolution; looking into this the 404 is letting us know it can't find the documents. The code is pointing to "URL.com/kreator.js/download/files.ext" 

Looking at the webroot of the default project there is no folder called "kreator.js". 
```
[me@myserver html] $ pwd
/var/www/html
[me@myserver html] $ ls
css       fonts        img        LICENSE       output        README.md
download  gulpfile.js  index.html  lib         node_modules  package.json  views
```

Solution/work around was create a kreator.js folder then copy the download folder into it

```
[me@myserver html] $ mkdir kreator.js
[me@myserver html] $ cp -a download kreator.js/
```

This has resolved the 404 errors and I'm now able to download the presentation. This could be a problem that was caused by using nginx as a web proxy. Nginx passes the application to http-server, however it will serve the static files (.js and .css scripts) directly in my configuration.

**Comment by piatra** [comment]
@FancyFane it's working for me locally & on github pages piatra.github.io/kreator.js it must be something related to your setup, I've noticed you are running from a different domain `myurl.com`.
What I can do is check path resolution in the application and see if I spot any problems.

**Comment by piatra** [comment]
I've spotted the problem. Expect a fix landing soon.

**Comment by piatra** [comment]
Let me know if this issue comes up again. Thanks!
